### PR TITLE
Add support for CSSSupportsRule

### PR DESCRIPTION
**Pull request by thomashigginbotham**
Error is no longer thrown when CSS contains @supports, and @media/@supports rules can be nested.

### CODE REVIEW

**Comment by Hypnosphi** [comment]
@NV is there anything that blocks merging and releasing this? Can I help in any way?

**Comment by NV** [comment]
The pull request looks good at the first glance, but it needs tests.

I apologize for not responding for so long.

**Comment by devrelm** [comment]
@thomashigginbotham Do you have time to add tests? If not, I can try to pick up your ticket and take a whack at it.

**Comment by thomashigginbotham** [comment]
@devrelm Sure, please do. I likely won't have time in the near future.

**Comment by devrelm** [comment]
@NV I added some tests and put up another PR over at #96

**Comment by NV** [comment]
Fixed in #96

**Comment by huchenme** [comment]
@NV can we do a new release to get in this fix?

**Comment by grahamlicence** [comment]
@huchenme it's available in 0.3.4

**Pull request closed without merging**
